{"@t":"2020-11-01T02:14:01.9364250Z","@mt":"Get 随机创建数据","SourceContext":"SerilogDemo.Controllers.WeatherForecastController","ActionId":"7e6db2a7-01f2-46ee-97ea-ea3f9135276b","ActionName":"SerilogDemo.Controllers.WeatherForecastController.Get (SerilogDemo)","RequestId":"0HM3U1F5OD29N:00000001","RequestPath":"/weatherforecast","SpanId":"|f5fae16f-4125062eeb3d52b9.","TraceId":"f5fae16f-4125062eeb3d52b9","ParentId":"","ConnectionId":"0HM3U1F5OD29N"}
{"@t":"2020-11-01T02:14:06.4787997Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"System.Exception: 自定义异常\r\n   at SerilogDemo.Controllers.WeatherForecastController.Get() in D:\\Resources\\GitFile\\Demo\\20-SerilogDemo\\SerilogDemo\\Controllers\\WeatherForecastController.cs:line 32\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"0HM3U1F5OD29N:00000001","RequestPath":"/weatherforecast","SpanId":"|f5fae16f-4125062eeb3d52b9.","TraceId":"f5fae16f-4125062eeb3d52b9","ParentId":"","ConnectionId":"0HM3U1F5OD29N"}
{"@t":"2020-11-01T02:18:15.6062879Z","@m":"Get 随机创建数据","@i":"6936e72c","SourceContext":"SerilogDemo.Controllers.WeatherForecastController","ActionId":"69ecb6f0-5c68-4abf-97da-76aed6a54cc6","ActionName":"SerilogDemo.Controllers.WeatherForecastController.Get (SerilogDemo)","RequestId":"0HM3U1HHN2QOM:00000001","RequestPath":"/weatherforecast","SpanId":"|a46092a2-4431cd8400719639.","TraceId":"a46092a2-4431cd8400719639","ParentId":"","ConnectionId":"0HM3U1HHN2QOM"}
{"@t":"2020-11-01T02:18:17.7222740Z","@m":"An unhandled exception has occurred while executing the request.","@i":"48a46595","@l":"Error","@x":"System.Exception: 自定义异常\r\n   at SerilogDemo.Controllers.WeatherForecastController.Get() in D:\\Resources\\GitFile\\Demo\\20-SerilogDemo\\SerilogDemo\\Controllers\\WeatherForecastController.cs:line 32\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"0HM3U1HHN2QOM:00000001","RequestPath":"/weatherforecast","SpanId":"|a46092a2-4431cd8400719639.","TraceId":"a46092a2-4431cd8400719639","ParentId":"","ConnectionId":"0HM3U1HHN2QOM"}
